#!/bin/bash

if [ -n "$CPFUNCS_DEBUG" ] && [ $CPFUNCS_DEBUG -gt 3 ]
    then
    set -x
fi

read -r -d '' PERL_READLINK_STR_2<<EOFMM
use Cwd "abs_path";
print abs_path(shift);
EOFMM


script_file=`which $0`
if [  -z "$script_file"  ]
then
        script_file=`perl -e "$PERL_READLINK_STR_2" $0`
fi
script_dir=`dirname $script_file`

source "$script_dir/cpfuncs"

DEF_MNTDIR=$(GetSmbMountDir)
DEF_BASEDIR=

gitbase_dir=$(GetGitDir)
DEF_BASEDIR=`basename $gitbase_dir`
if [ "$DEF_BASEDIR" = "/" ]
then
        DEF_BASEDIR=""
fi

basedir=$DEF_BASEDIR
mntdir=$DEF_MNTDIR
verbose=0

source extargsparse4sh

read -r -d '' OPTIONS<<EOFMM
    {
        "verbose|v" : "+",
        "mntdir|m" : "$DEF_MNTDIR",
        "basedir|b" : "$DEF_BASEDIR",
        "\$<args>" : "+"
    }
EOFMM


parse_command_line "$OPTIONS" "$@"


if [ -z "$mntdir" ]
        then
        echo "please specify mountdir by -m|--mntdir or mount them or export CP_SMB_DIR environment value" >/dev/stderr
        exit 4
fi


for item in ${args[@]}
do
        if [ "$item" = "--" ]
            then
            continue
        fi
        _absitem=`perl -e "$PERL_READLINK_STR_2" $item`
        _issubdir=$(IsSub "$gitbase_dir" "$_absitem")
        if [ $_issubdir -gt 0 ]
                then
                curitem=$(GetSubDir "$gitbase_dir" "$_absitem")
                Debug "todir [$mntdir/$basedir] curitem [$curitem] gitbase_dir[$gitbase_dir]"
                CopyTo "$mntdir/$basedir" "$curitem" "$gitbase_dir"
        else
                Warn "item($item) not subdir in ($gitbase_dir)" >&2
        fi
done

