#!/bin/bash

if [ -n "$CPFUNCS_DEBUG" ] && [ $CPFUNCS_DEBUG -gt 3 ]
    then
    set -x
fi

read -r -d '' PERL_READLINK_STR_2<<EOFMM
use Cwd "abs_path";
print abs_path(shift);
EOFMM


script_file=`which $0`
if [  -z "$script_file"  ]
then
        script_file=`perl -e "$PERL_READLINK_STR_2" $0`
fi
script_dir=`dirname $script_file`

source "$script_dir/cpfuncs"

DEF_MNTDIR=$(GetSmbMountDir)
DEF_BASEDIR=

gitbase_dir=$(GetGitDir)
DEF_BASEDIR=`basename $gitbase_dir`
if [ "$DEF_BASEDIR" = "/" ]
then
        DEF_BASEDIR=""
fi

basedir=$DEF_BASEDIR
mntdir=$DEF_MNTDIR
verbose=0

source extargsparse4sh

read -r -d '' OPTIONS<<EOFMM
    {
        "verbose|v" : "+",
        "mntdir|m" : "$DEF_MNTDIR",
        "basedir|b" : "$DEF_BASEDIR",
        "\$<args>" : "+"
    }
EOFMM



CopyTo()
{
        local _todir=$1
        local _frombase=$2
        local _basedir=$3
        local _osname=`uname -s | tr [:upper:] [:lower:]`

        Debug "from $_basedir/$_frombase to $_todir/$_frombase"
        if [ -d "$_basedir/$_frombase" ]
        then
                _bname1="$_todir/$_frombase"
                if [ "$_osname" = "darwin" ]
                    then
                    if [ ! -d "$_bname1" ]
                        then
                        Debug "mkdir -p ($_bname1)"
                        ${SUDO_PREFIX} $MKDIR -p "$_bname1"
                    fi
                    Debug "[$_basedir/$_frombase] [$_bname1]"
                    ${SUDO_PREFIX} ${CP} -r -f "$_basedir/$_frombase" "$_bname1"
                else
                    _bname=`dirname $_bname1`
                    if [ ! -d "$_bname" ]
                    then
                            Debug "mkdir -p ($_bname)"
                            ${SUDO_PREFIX} $MKDIR -p "$_bname"
                    fi
                
                    Debug "[$_basedir/$_frombase] [$_bname]"
                    ${SUDO_PREFIX}         ${CP}  -r -f  "$_basedir/$_frombase" "$_bname"
                fi
        else
                _bname=`dirname $_todir/$_frombase`
                if [ ! -d "$_bname" ]
                        then
                        ${SUDO_PREFIX} $MKDIR -p $_bname
                fi
                Debug "[$_basedir/$_frombase] => [$_todir/$_frombase]"
                ${SUDO_PREFIX} ${CP} -f "$_basedir/$_frombase" "$_todir/$_frombase"
        fi
}

parse_command_line "$OPTIONS" "$@"


if [ -z "$mntdir" ]
        then
        echo "please specify mountdir by -m|--mntdir or mount them or export CP_SMB_DIR environment value" >/dev/stderr
        exit 4
fi


for item in "${args[@]}"
do
        if [ "$item" = "--" ]
            then
            continue
        fi
        _absitem=`perl -e "$PERL_READLINK_STR_2" $item`
        _issubdir=$(IsSub "$gitbase_dir" "$_absitem")
        if [ $_issubdir -gt 0 ]
                then
                curitem=$(GetSubDir "$gitbase_dir" "$_absitem")
                CopyTo "$mntdir/$basedir" "$curitem" "$gitbase_dir"
        else
                Warn "item($item) not subdir in ($gitbase_dir)" >&2
        fi
done

