#! /bin/bash


INFO_LEVEL=2
DEBUG_LEVEL=3
WARN_LEVEL=1
ERROR_LEVEL=0

function __Debug()
{
        local _fmt=$1
        local _osname=`uname -s | tr [:upper:] [:lower:]`
        shift
        local _backstack=0
        if [ $# -gt 0 ]
                then
                _backstack=$1
        fi
        
        _fmtstr=""
        if [ $verbose -gt $INFO_LEVEL ]
                then
                local _filestack=`expr $_backstack \+ 1`
                _fmtstr="${BASH_SOURCE[$_filestack]}:${BASH_LINENO[$_backstack]} "
        fi

        _fmtstr="$_fmtstr$_fmt"
        if [ "$_osname" = "darwin" ]
                then
                ${ECHO} "$_fmtstr" >&2
        else
                ${ECHO} -e "$_fmtstr" >&2
        fi
}

function Debug()
{
        local _fmt=$1
        shift
        local _backstack=0
        if [ $# -gt 0 ]
                then
                _backstack=$1
        fi
        _backstack=`expr $_backstack \+ 1`
        
        if [ $verbose -ge $DEBUG_LEVEL ]
                then
                __Debug "$_fmt" "$_backstack"
        fi
        return
}

function Info()
{
        local _fmt=$1
        shift
        local _backstack=0
        if [ $# -gt 0 ]
                then
                _backstack=$1
        fi
        _backstack=`expr $_backstack \+ 1`
        
        if [ $verbose -ge $INFO_LEVEL ]
                then
                __Debug "$_fmt" "$_backstack"
        fi
        return
}

function Warn()
{
        local _fmt=$1
        shift
        local _backstack=0
        if [ $# -gt 0 ]
                then
                _backstack=$1
        fi
        _backstack=`expr $_backstack \+ 1`
        
        if [ $verbose -ge $WARN_LEVEL ]
                then
                __Debug "$_fmt" "$_backstack"
        fi
        return
}



function ErrorExit()
{
        local _ec=$1
        local _fmt="$2"
        local _osname=`uname -s | tr [:upper:] [:lower:]`
        local _backstack=0
        if [ $# -gt 2 ]
                then
                _backstack=$3
        fi
        local _fmtstr=""

        if [ $verbose -gt $INFO_LEVEL ]
                then
                _fmtstr="${BASH_SOURCE[$_backstack]}:${BASH_LINENO[$_backstack]} "
        fi
        _fmtstr="$_fmtstr$_fmt"
        if [ "$_osname" = "darwin" ]
        	then
        	echo "$_fmtstr" >&2
        else
        	echo -e "$_fmtstr" >&2
    	fi
        exitcode=$_ec
        exit $_ec
}
